CC = aarch64-linux-gnu-gcc
LD = aarch64-linux-gnu-ld

# Flags for C compilation
CFLAGS = -g -pedantic -Wall -Wextra -fPIC -std=gnu2x -MMD -fno-builtin-strlen

# Flags for Assembly compilation
ASFLAGS = -g -MMD

# Flags for Linking
LDFLAGS = -g -N -Ttext=0x10000

# The root target
all: kernel.elf

# Link object files and library to create the final OS binary
kernel.elf: kernel.o boot.o progress.o libos.a
	$(LD) $(LDFLAGS) -o kernel.elf kernel.o boot.o progress.o libos.a

# Compile C source into object file
kernel.o: kernel.c
	$(CC) $(CFLAGS) -c kernel.c -o kernel.o

# Assemble boot source into object file
boot.o: boot.S
	$(CC) $(ASFLAGS) -c boot.S -o boot.o

# Assemble progress source into object file
progress.o: progress.S
	$(CC) $(ASFLAGS) -c progress.S -o progress.o

# Delete all compiled and generated files
clean:
	rm -f *.o *.d kernel.elf

# Launch the OS in QEMU
run: kernel.elf
	qemu-system-aarch64 -machine raspi3b -kernel kernel.elf

# Launch the OS in QEMU paused and waiting for a GDB debugger connection
debug: kernel.elf
	qemu-system-aarch64 -machine raspi3b -kernel kernel.elf -S -s

# Include the .d dependency files generated by the -MMD flag
-include *.d
